### ISSUE TITLE
Net' object has no attribute 'pooling_ratio_1_2'

### ISSUE THREAD

**Issue by amiroft** [nadgeri14/KGPool#6]
Hi
Through my attempts to run your code i faced this error which I have no idea about it

`ERROR:test:Failed after 0:02:49!
Traceback (most recent call last):
  File "/home/amir/PycharmProjects/Kgpool/venv/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/amir/PycharmProjects/Kgpool/venv/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/amir/PycharmProjects/Kgpool/venv/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/amir/PycharmProjects/Kgpool/venv/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/home/amir/PycharmProjects/Kgpool/Context-Aggregator/train.py", line 180, in main
    model = get_model(model_name)(model_params, embeddings, max_sent_len, n_out, kgpool_args, char2idx)
  File "/home/amir/PycharmProjects/Kgpool/Context-Aggregator/models/our_models.py", line 78, in __init__
    self.kgpool = Net(kgpool_args, embeddings, kgpool_char2idx)
  File "/home/amir/PycharmProjects/Kgpool/Context-Aggregator/../KGPool/networks.py", line 80, in __init__
    self.pool1 = KGPool(self.nhid, ratio=self.pooling_ratio_1_2, dynamic_pooling=self.dynamic_pooling1)
  File "/home/amir/PycharmProjects/Kgpool/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Net' object has no attribute 'pooling_ratio_1_2'`

**Comment by nadgeri14** [comment]
Hi,
Can you please share the command you used for training and also the path from where you executed the code. 
Thanks 
Abhishek

**Comment by amiroft** [comment]
I tried running train.py @ context-aggregator

**Comment by amiroft** [comment]
I solved above issue with some trick in order to run the code , 
For now i have this question:
I have NameError exception for "sentence_input"
in our_model.py where you defined GPGNN model and when you wanted to make 'expanded_sentence_input' you have not define sentece_input variable. what is this sentence_input how can we bring it ?

**Comment by nadgeri14** [comment]
Hi 
So, if we try to look back, then the sentence_input is extracted from the variable [train_as_indices[0]](https://github.com/nadgeri14/KGPool/blob/master/%20Context-Aggregator/train.py#L195). The train_as_indices is derived from the function call [graphs_to_indices](https://github.com/nadgeri14/KGPool/blob/master/%20Context-Aggregator/train.py#L155) and the training data is derived from function [load_relation_graphs_from_file](https://github.com/nadgeri14/KGPool/blob/master/%20Context-Aggregator/train.py#L124). 
Hope it helps

Can you ensure the training file is correct? 
Best
Abhishek

**Comment by amiroft** [comment]
Hi 
As I think this issue has different title ,I close this issue and open another one,
Thanks
